### ISSUE TITLE
napa pollutes node_modules causing problems with npm shrinkwrap 

### ISSUE THREAD

**Issue by mzgoddard** [shama/ember-templates-loader#6]
A project I'm on is using npm shrinkwrap to freeze versions for our project for deployable versions. `npm shrinkwrap` intentionally will not produce a shrinkwrap if there are any extraneous modules in node_modules. `napa` usage breaks npm shrinkwrap.

**Comment by mzgoddard** [comment]
I'm not sure how best to resolve this but `node_modules` must be only npm `dependencies` and `devDependencies`.

**Comment by shama** [comment]
Ref https://github.com/shama/napa/issues/20

But I'll just include ember directly in the repo to fix for now.
