### ISSUE TITLE
Ember 0.11.1 template.revision

### ISSUE THREAD

**Issue by Coobaha** [shama/ember-templates-loader#8]
@shama
Ember now asserts template revision:
https://github.com/emberjs/ember.js/issues/10447
https://github.com/tildeio/htmlbars/pull/296

**Comment by shama** [comment]
Thanks, I'll take a look shortly. We haven't updated to 1.11 yet.

**Comment by gnarf** [comment]
We are trying to make this same bump, is there some way I can help here?

**Comment by shama** [comment]
@gnarf Yep! Any help would be very much appreciated. We are still on 1.10 but have plans to upgrade to 1.12 within the next month.

I've added you and @mzgoddard as owners. Feel free to push as needed. Thanks!

**Comment by gnarf** [comment]
Opened up PR #9 to jump to 0.12.0 -- How do you feel about keeping the ember-templates-loader versions in sync with Ember version the compiler is sourced from?

**Comment by shama** [comment]
Rad thank you @gnarf! Keeping in step with Ember's version sounds fine to me. Usually it's a little problematic when you need to update more than the lib your stepping with, such as`1.12.1-2` but this lib is so thin that's likely not going to happen. :)

**Comment by gnarf** [comment]
@shama I'll let you land my PR and publish then :)

**Comment by shama** [comment]
Fixed by 072078da1c73df37acc039adf1cbe05e49083357
